services:
  - type: web
    name: banking-dashboard
    runtime: docker
    dockerfilePath: ./quickstart/python/Dockerfile.dev
    dockerContext: .
    plan: free
    region: oregon
    healthCheckPath: /health
